version: '2'
services:
    albanjar-app:
        image: albanjar
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://albanjar-postgresql:5432/Albanjar
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    albanjar-postgresql:
        extends:
            file: postgresql.yml
            service: albanjar-postgresql
