version: '2'
services:
    albanjar-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/Albanjar/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=Albanjar
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
